apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # Directory on the node. For local testing with Docker Desktop / minikube this will be on the node filesystem.
    path: /var/lib/k8s/tasks
    type: DirectoryOrCreate
  claimRef:
    # Pre-bind to the namespace 'default' and the PVC named 'tasks-data-pvc'
    namespace: default
    name: tasks-data-pvc
