apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webserver
  template:
    metadata:
      labels:
        app: my-webserver
    spec:
      containers:
      - name: my-webserver
        image: alkatzo/my-webserver:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-webserver-service
spec:
  selector:
    app: my-webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
