apiVersion: v1
kind: Service
metadata:
  name: second-app-service
  labels:
    group: second-app
spec:
  selector:
    app: second-app
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
