version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      POSTGRES_CONNECTION_URI: 'postgres://postgres:password@postgres:5432/users'
      AUTH_API_ADDRESSS: 'auth:3000'