---
# ExternalName service to reference slave namespace service
apiVersion: v1
kind: Service
metadata:
  name: ui-service-slave-proxy
  namespace: task-system-master
spec:
  type: ExternalName
  externalName: ui-service.task-system-slave.svc.cluster.local
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: task-system-master
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /master
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 80
      - path: /slave
        pathType: Prefix
        backend:
          service:
            name: ui-service-slave-proxy
            port:
              number: 80
