---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.master }}
  labels:
    app: task-system
    role: master
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.slave }}
  labels:
    app: task-system
    role: slave
