{{- range $role, $namespace := .Values.namespaces }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-executor
  namespace: {{ $namespace }}
  labels:
    app: task-executor
    role: {{ $role }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-executor
      role: {{ $role }}
  template:
    metadata:
      labels:
        app: task-executor
        role: {{ $role }}
    spec:
      containers:
      - name: task-executor
        image: {{ $.Values.registry }}/{{ $.Values.repository }}:{{ $.Values.images.taskExecutor }}
        command: ["python", "app.py"]
        env:
        {{- include "postgres.env" $namespace | nindent 8 }}
        resources:
          {{- toYaml $.Values.resources.taskExecutor | nindent 10 }}
{{- end }}
