apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  type: NodePort
  ports:
    - protocol: TCP
      port: 80           # cluster port
      targetPort: 3000   # container port
      nodePort: 30080    # static port exposed on Minikube node
