{{- if .Values.replication.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.replication.namespaces.master }}
  labels:
    app: task-system
    role: master
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.replication.namespaces.slave }}
  labels:
    app: task-system
    role: slave
{{- end }}
